id: 1
server:
  httpPort: 8801
input:
  redis:
    addresses: [127.0.0.1:6300]
    type: cluster
  rdbParallel: 4
  mode: dynamic
channel:
  storer:
    dirPath: /tmp/redisgunyu-cluster
    maxSize: 10737418240
output:
  redis:
    addresses: [127.0.0.1:6310]
    type: cluster
  resumeFromBreakPoint: true
  keyExists: replace
  metric: true
  targetDb: -1
log:
  level: info
  handler:
    stdout: true
cluster:
  groupName: redis1
  leaseTimeout: 3s
  metaEtcd: 
    endpoints:
      - 127.0.0.1:2379
  replica:
    listen: "0.0.0.0:8088"
    listenPeer: "127.0.0.1:8088"