id: 2
server:
  httpPort: 18801
  gracefullStopTimeout: 1s
input:
  redis:
    addresses: [127.0.0.1:16300]
    type: cluster
  rdbParallel: 4
  mode: dynamic
  syncDelayTestKey: redis-GunYu-syncDelay-testKey
channel:
  storer:
    dirPath: /tmp/redisgunyu-cluster2
    maxSize: 209715200
    logSize: 20971520
  staleCheckpointDuration: 10m
output:
  redis:
    addresses: [127.0.0.1:16310]
    type: cluster
  resumeFromBreakPoint: true
  keyExists: replace
  metric: true
  targetDb: -1
log:
  level: info
  handler:
    stdout: true
cluster:
  groupName: redis1
  leaseTimeout: 3s
  metaEtcd: 
    endpoints:
      - 127.0.0.1:2379
  replica:
    listen: "0.0.0.0:18088"
    listenPeer: "127.0.0.1:18088"