input:
  redis:
    addresses: [127.0.0.1:6700]
    type: standalone
channel:
  storer:
    dirPath: /tmp/redisgunyu4
    maxSize: 10737418
    logSize: 1097152
output:
  keepaliveTicker: 100s
  redis:
    addresses: [127.0.0.1:6707]
    type: standalone
log:
  level: info
  handler:
    stdout: true
  