id: 1
httpProfile: 18000
input:
  redis:
    addresses: [127.0.0.1:6707]
    type: standalone
  rdbParallel: 1
channel:
  storer:
    dirPath: /tmp/redisgunyu
    maxSize: 10737418240
output:
  redis:
    addresses: [127.0.0.1:6717]
    type: standalone
  resumeFromBreakPoint: true
  keyExists: replace
  metric: true
  targetDb: -1
  bigKeyThreshold: 200000
log:
  level: debug
  handler:
    stdout: true
  